drop table if exists dws_text_analysis_detail;
drop table if exists dwd_comment_clean;
drop table if exists dwd_danmaku_clean;
drop table if exists ads_up_performance;
drop table if exists ads_keyword_top;
drop table if exists ads_danmaku_timeline;
drop table if exists ads_sentiment_by_date;
drop table if exists ads_video_sentiment;
drop table if exists ads_video_heat_rank;
drop table if exists ops_task_status;
drop table if exists ops_task;

create table ads_video_heat_rank (
    bvid varchar(32) primary key,
    title varchar(255),
    up_name varchar(100),
    category varchar(64),
    view_count bigint,
    like_count bigint,
    coin_count bigint,
    favorite_count bigint,
    reply_count bigint,
    danmaku_count bigint,
    heat_score double,
    rank_no int
);

create table ads_video_sentiment (
    bvid varchar(32) primary key,
    title varchar(255),
    avg_sentiment double,
    positive_count bigint,
    neutral_count bigint,
    negative_count bigint,
    total_count bigint,
    positive_ratio double,
    negative_ratio double
);

create table ads_sentiment_by_date (
    stat_date date primary key,
    comment_count bigint,
    danmaku_count bigint,
    avg_sentiment double,
    negative_ratio double
);

create table ads_danmaku_timeline (
    id bigint generated by default as identity primary key,
    bvid varchar(32),
    time_bucket int,
    danmaku_count bigint,
    avg_sentiment double,
    top_words clob
);

create table ads_keyword_top (
    id bigint generated by default as identity primary key,
    dimension_type varchar(32),
    dimension_value varchar(128),
    word varchar(64),
    word_count bigint,
    rank_no int
);

create table ads_up_performance (
    up_name varchar(100) primary key,
    video_count bigint,
    avg_view_count double,
    avg_heat_score double,
    avg_sentiment double,
    total_like_count bigint
);

create table dwd_comment_clean (
    id bigint generated by default as identity primary key,
    bvid varchar(32),
    rpid varchar(64) unique,
    user_mid varchar(64),
    user_name varchar(128),
    text clob,
    like_count bigint,
    crawled_at timestamp,
    source_type varchar(16),
    raw_content clob,
    clean_content clob,
    content_length int,
    clean_label varchar(32),
    clean_score double,
    is_valid_text smallint,
    clean_reason varchar(64),
    created_at timestamp
);

create table dwd_danmaku_clean (
    id bigint generated by default as identity primary key,
    bvid varchar(32),
    cid varchar(64),
    video_time_seconds double,
    text clob,
    crawled_at timestamp,
    danmaku_id varchar(128) unique,
    source_type varchar(16),
    raw_content clob,
    clean_content clob,
    content_length int,
    clean_label varchar(32),
    clean_score double,
    is_valid_text smallint,
    clean_reason varchar(64),
    created_at timestamp
);

create table dws_text_analysis_detail (
    id bigint generated by default as identity primary key,
    source_type varchar(16),
    source_id varchar(128),
    bvid varchar(32),
    clean_content clob,
    tokens clob,
    keywords clob,
    sentiment_score double,
    sentiment_label varchar(16),
    model_version varchar(64),
    created_at timestamp
);

create table ops_task_status (
    task_id varchar(255) primary key,
    status varchar(32) not null,
    updated_at timestamp default current_timestamp,
    created_at timestamp default current_timestamp
);

create table ops_task (
    task_id varchar(255) primary key,
    title varchar(255) not null,
    level varchar(32) not null,
    type varchar(32) not null,
    text clob not null,
    bvid varchar(32),
    source varchar(64) default 'system' not null,
    sort_no int default 100 not null,
    is_active smallint default 1 not null,
    created_at timestamp default current_timestamp,
    updated_at timestamp default current_timestamp
);
