<template>
  <section class="collector-layout">
    <section class="panel collector-form-panel" v-loading="loading">
      <div class="panel-header"><div><div class="panel-title">爬虫任务</div><div class="panel-desc">按爬虫平台 OpenAPI 创建、查询、取消和恢复指定视频页面的采集任务。</div></div><el-tag :type="status.configured ? 'success' : 'warning'">{{ status.configured ? '已接入' : '暂未接入' }}</el-tag></div>
      <el-alert :title="status.message" :type="status.configured ? 'success' : 'warning'" :closable="false" show-icon class="capability-alert" />
      <el-form label-position="top" class="collector-form">
        <el-form-item label="视频或页面地址" required><el-input v-model.trim="jobForm.sourceUrl" placeholder="请输入爬虫平台可访问的视频或页面 URL" /></el-form-item>
        <div class="collector-inline-grid"><el-form-item label="认证档案" required><el-select v-model="jobForm.authProfileId" placeholder="选择认证档案" :disabled="!status.configured"><el-option v-for="profile in profiles" :key="profile.profile_id" :label="`${profile.profile_name}（${profile.platform}）`" :value="profile.profile_id" :disabled="profile.status !== 'active'" /></el-select></el-form-item><el-form-item label="最大视频数"><el-input-number v-model="jobForm.videoLimit" :min="1" :max="500" controls-position="right" /></el-form-item></div>
        <el-form-item label="策略参数 JSON"><el-input v-model="strategyText" type="textarea" :rows="5" placeholder='例如 {"max_root_comments":100,"fetch_all_danmaku":true}' /></el-form-item>
        <div class="collector-actions"><el-button :icon="Refresh" :loading="loading" @click="load">刷新认证档案</el-button><el-button type="primary" :icon="Upload" :loading="submitting" :disabled="!status.configured" @click="submitJob">创建爬虫任务</el-button></div>
      </el-form>
    </section>
    <section class="panel collector-help-panel"><div class="panel-header"><div><div class="panel-title">接口能力</div><div class="panel-desc">仅展示 openapi(2).json 已定义的任务能力。</div></div></div><div class="collector-help"><div><strong>已支持</strong><span>认证档案创建、校验、启停；创建、查询、取消、恢复爬虫任务。</span></div><div><strong>可采集数据</strong><span>视频指标、评论，以及弹幕或字幕等带时间文本。</span></div><div><strong>暂未提供</strong><span>关键词、账号、热门内容搜索与任务列表接口，因此本页面不展示相应功能。</span></div><div><strong>平台配置</strong><span>设置后端 CRAWLER_BASE_URL 和可选的 CRAWLER_API_KEY 后启用。</span></div></div></section>
  </section>
  <section class="panel video-panel"><div class="panel-header"><div><div class="panel-title">认证档案</div><div class="panel-desc">认证档案由爬虫平台保存，本平台不会读取或存储登录凭据。</div></div><el-button :disabled="!status.configured" @click="showProfileForm = !showProfileForm">{{ showProfileForm ? '收起' : '新建档案' }}</el-button></div><el-form v-if="showProfileForm" :model="profileForm" label-position="top" class="collector-form"><div class="collector-inline-grid"><el-form-item label="平台代码"><el-input v-model.trim="profileForm.platform" placeholder="例如 bilibili" /></el-form-item><el-form-item label="档案名称"><el-input v-model.trim="profileForm.profileName" placeholder="例如 默认登录档案" /></el-form-item></div><el-form-item label="浏览器档案目录"><el-input v-model.trim="profileForm.profileDirectory" placeholder="由爬虫平台所在机器可访问的目录" /></el-form-item><el-button type="primary" :loading="creatingProfile" @click="submitProfile">保存认证档案</el-button></el-form><el-table :data="profiles" empty-text="暂无认证档案" style="width:100%"><el-table-column prop="profile_name" label="档案名称" min-width="180" /><el-table-column prop="platform" label="平台" width="130" /><el-table-column prop="status" label="状态" width="120"><template #default="{ row }"><el-tag :type="profileStatusType(row.status)">{{ profileStatusLabel(row.status) }}</el-tag></template></el-table-column><el-table-column prop="last_verified_at" label="最近校验" width="180"><template #default="{ row }">{{ formatDateTime(row.last_verified_at) }}</template></el-table-column><el-table-column label="操作" width="210"><template #default="{ row }"><el-button link type="primary" @click="verifyProfile(row)">校验</el-button><el-button link :type="row.status === 'disabled' ? 'success' : 'warning'" @click="toggleProfile(row)">{{ row.status === 'disabled' ? '启用' : '停用' }}</el-button></template></el-table-column></el-table></section>
  <section v-if="currentJob" class="panel video-panel" v-loading="jobLoading"><div class="panel-header"><div><div class="panel-title">当前爬虫任务</div><div class="panel-desc">{{ currentJob.job_id }}</div></div><div class="collector-actions"><el-button :icon="Refresh" @click="refreshJob">刷新</el-button><el-button type="warning" :disabled="!canResume" @click="resumeJob">恢复</el-button><el-button type="danger" :disabled="isFinished" @click="cancelJob">取消</el-button></div></div><div class="collector-result-grid"><div><span>状态</span><strong>{{ currentJob.status || '--' }}</strong></div><div><span>创建时间</span><strong>{{ formatDateTime(currentJob.created_at) }}</strong></div><div><span>开始时间</span><strong>{{ formatDateTime(currentJob.started_at) }}</strong></div><div><span>结束时间</span><strong>{{ formatDateTime(currentJob.finished_at) }}</strong></div></div><div class="collector-detail-body"><div><div class="collector-detail-title">任务进度</div><pre>{{ pretty(currentJob.progress) }}</pre></div><div><div class="collector-detail-title">模块状态</div><pre>{{ pretty(currentJob.module_states) }}</pre></div></div></section>
</template>

<script setup>
import { computed, onMounted, reactive, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { Refresh, Upload } from '@element-plus/icons-vue'
import { cancelCrawlJob, createAuthProfile, createCrawlJob, fetchAuthProfiles, fetchCrawlJob, fetchCrawlerStatus, resumeCrawlJob, setAuthProfileEnabled, verifyAuthProfile } from '@/api/crawler'

const loading = ref(false); const submitting = ref(false); const creatingProfile = ref(false); const jobLoading = ref(false); const showProfileForm = ref(false); const profiles = ref([]); const currentJob = ref(null)
const status = reactive({ configured: false, message: '正在检查爬虫平台配置' }); const jobForm = reactive({ sourceUrl: '', authProfileId: '', videoLimit: 1 }); const profileForm = reactive({ platform: '', profileName: '', profileDirectory: '' }); const strategyText = ref('{}')
const isFinished = computed(() => ['completed', 'success', 'failed', 'cancelled', 'canceled'].includes(String(currentJob.value?.status || '').toLowerCase())); const canResume = computed(() => ['failed', 'cancelled', 'canceled'].includes(String(currentJob.value?.status || '').toLowerCase()))
onMounted(load)
async function load() { loading.value = true; try { Object.assign(status, await fetchCrawlerStatus()); profiles.value = status.configured ? await fetchAuthProfiles() : [] } catch (error) { ElMessage.error(error.message || '爬虫平台状态读取失败') } finally { loading.value = false } }
async function submitJob() { if (!jobForm.sourceUrl || !jobForm.authProfileId) return ElMessage.warning('请填写页面地址并选择认证档案'); let strategy; try { strategy = strategyText.value.trim() ? JSON.parse(strategyText.value) : {} } catch { return ElMessage.error('策略参数必须是合法 JSON') } submitting.value = true; try { currentJob.value = await createCrawlJob({ source_url: jobForm.sourceUrl, auth_profile_id: jobForm.authProfileId, video_limit: jobForm.videoLimit, strategy }); ElMessage.success('爬虫任务已创建') } catch (error) { ElMessage.error(error.message || '创建爬虫任务失败') } finally { submitting.value = false } }
async function submitProfile() { if (!profileForm.platform || !profileForm.profileName || !profileForm.profileDirectory) return ElMessage.warning('请完整填写认证档案信息'); creatingProfile.value = true; try { await createAuthProfile({ platform: profileForm.platform, profile_name: profileForm.profileName, profile_directory: profileForm.profileDirectory }); Object.assign(profileForm, { platform: '', profileName: '', profileDirectory: '' }); showProfileForm.value = false; await load(); ElMessage.success('认证档案已创建') } catch (error) { ElMessage.error(error.message || '创建认证档案失败') } finally { creatingProfile.value = false } }
async function verifyProfile(profile) { try { await verifyAuthProfile(profile.profile_id); await load(); ElMessage.success('认证档案已校验') } catch (error) { ElMessage.error(error.message || '认证档案校验失败') } }
async function toggleProfile(profile) { try { await setAuthProfileEnabled(profile.profile_id, profile.status === 'disabled'); await load(); ElMessage.success(profile.status === 'disabled' ? '认证档案已启用' : '认证档案已停用') } catch (error) { ElMessage.error(error.message || '认证档案状态更新失败') } }
async function refreshJob() { if (!currentJob.value?.job_id) return; jobLoading.value = true; try { currentJob.value = await fetchCrawlJob(currentJob.value.job_id) } catch (error) { ElMessage.error(error.message || '任务查询失败') } finally { jobLoading.value = false } }
async function cancelJob() { try { await ElMessageBox.confirm('确认取消当前爬虫任务？', '取消任务', { type: 'warning' }); currentJob.value = await cancelCrawlJob(currentJob.value.job_id); ElMessage.success('任务已取消') } catch (error) { if (error !== 'cancel') ElMessage.error(error.message || '取消任务失败') } }
async function resumeJob() { try { currentJob.value = await resumeCrawlJob(currentJob.value.job_id); ElMessage.success('任务已恢复') } catch (error) { ElMessage.error(error.message || '恢复任务失败') } }
function profileStatusType(value) { return { active: 'success', expired: 'warning', disabled: 'info' }[value] || 'info' }; function profileStatusLabel(value) { return { active: '可用', expired: '已过期', disabled: '已停用' }[value] || value || '--' }; function formatDateTime(value) { return value ? String(value).replace('T', ' ').slice(0, 19) : '--' }; function pretty(value) { return JSON.stringify(value || {}, null, 2) }
</script>
