<template><section class="panel video-panel" v-loading="loading"><div class="panel-header"><div><div class="panel-title">指标管理</div><div class="panel-desc">统一维护指标展示名称、单位、口径和跨平台可比性。</div></div><el-button type="primary" @click="load">刷新</el-button></div><el-table :data="metrics" empty-text="暂无指标配置" style="width:100%"><el-table-column prop="displayName" label="指标名称" min-width="160"><template #default="{row}"><strong>{{row.displayName}}</strong><div class="table-sub">{{row.metricKey}}</div></template></el-table-column><el-table-column prop="unit" label="单位" width="110" /><el-table-column prop="scope" label="口径范围" width="130" /><el-table-column label="可跨平台比较" width="150"><template #default="{row}"><el-tag :type="row.comparable?'success':'info'">{{row.comparable?'可以':'不可以'}}</el-tag></template></el-table-column><el-table-column label="操作" width="100"><template #default="{row}"><el-button link type="primary" @click="edit(row)">编辑</el-button></template></el-table-column></el-table><el-dialog v-model="visible" title="编辑指标" width="min(620px,94vw)"><el-form label-position="top"><el-form-item label="指标名称"><el-input v-model.trim="form.displayName"/></el-form-item><el-form-item label="单位"><el-select v-model="form.unit"><el-option label="次数" value="count"/><el-option label="比例" value="ratio"/><el-option label="分数" value="score"/><el-option label="百分位" value="percentile"/><el-option label="原始值" value="raw"/></el-select></el-form-item><el-form-item label="口径范围"><el-select v-model="form.scope"><el-option label="内容" value="content"/><el-option label="平台" value="platform"/><el-option label="跨平台" value="cross_platform"/></el-select></el-form-item><el-form-item label="指标说明"><el-input v-model.trim="form.definition" type="textarea" :rows="3"/></el-form-item><el-switch v-model="form.comparable" active-text="允许跨平台比较" inactive-text="仅平台内比较"/></el-form><template #footer><el-button @click="visible=false">取消</el-button><el-button type="primary" :loading="saving" @click="save">保存</el-button></template></el-dialog></section></template>
<script setup>
import { onMounted, reactive, ref } from 'vue'
import { ElMessage } from 'element-plus'
import { fetchMetricConfigs, saveMetricConfig } from '@/api/platform'
const loading=ref(false),saving=ref(false),metrics=ref([]),visible=ref(false),form=reactive({metricKey:'',displayName:'',unit:'count',scope:'content',definition:'',comparable:false})
onMounted(load)
async function load(){loading.value=true;try{metrics.value=await fetchMetricConfigs()}catch(e){ElMessage.error(e.message||'指标配置加载失败')}finally{loading.value=false}}
function edit(row){Object.assign(form,row);visible.value=true}
async function save(){if(!form.displayName){ElMessage.warning('请填写指标名称');return}saving.value=true;try{await saveMetricConfig(form.metricKey,{displayName:form.displayName,unit:form.unit,scope:form.scope,definition:form.definition,comparable:form.comparable});ElMessage.success('指标配置已保存');visible.value=false;await load()}catch(e){ElMessage.error(e.message||'指标配置保存失败')}finally{saving.value=false}}
</script>
